g++ convert_onnx_auto.cpp -o convert_onnx_auto \
    -std=c++17 \
    -O3 \
    -I/usr/local/cuda/include \
    -I/usr/include/aarch64-linux-gnu \
    -I/usr/include/python3.8 \
    -L/usr/local/cuda/lib64 \
    -L/usr/lib/aarch64-linux-gnu \
    -lnvinfer \
    -lnvonnxparser \
    -lnvinfer_plugin \
    -lcudart \
    -lpython3.8 \
    -lspdlog \
    -lfmt \
    -lpthread \
    -Wl,-rpath,/usr/local/cuda/lib64 \
    -Wl,-rpath,/usr/lib/aarch64-linux-gnu